---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Code Review

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - '**'
    # Remove the line above to run when pushing to master
  pull_request:
    branches: [master, dev]

###############
# Set the Job #
###############
jobs:
  Linter:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Install npm dependencies
        run : npm install

      - name: Lint code base
        run : npm run lint
  UnitTest:
    # Name the Job
    name: Unit Test Cases
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Install npm dependencies
        run : npm install

      - name: Run unit test cases
        run : npm run test